import { Campaign, User } from "@/types";

export const LIST_OF_CAMPAIGN_Types: string[] = [
  "Marketing",
  "Educational",
  "Governmental",
];

export const LIST_OF_CONTACTS: User[] = [
  { id: 0, name: "Contact Zero" },
  { id: 1, name: "Contact One" },
  { id: 2, name: "Contact Two" },
  { id: 3, name: "Contact Three" },
  { id: 4, name: "Contact Four" },
  { id: 5, name: "Contact Five" },
  { id: 6, name: "Contact Six" },
  { id: 7, name: "Contact Seven" },
  { id: 8, name: "Contact Eight" },
  { id: 9, name: "Contact Nine" },
  { id: 10, name: "Contact Ten" },
];

export const LIST_OF_CAMPAIGNS: Campaign[] = [
  {
    id: "123456",
    name: "First One",
    creation_date: new Date(),
    type: "Governmental",
    contacts: [1, 2, 3, 4, 5],
  },
  {
    id: "123456",
    name: "Second One",
    creation_date: new Date(),
    type: "Marketing",
    contacts: [1, 2, 3, 4, 5],
  },
  {
    id: "123456",
    name: "3rd One",
    creation_date: new Date(),
    type: "Marketing",
    contacts: [1, 2, 3, 4, 5],
  },
  {
    id: "123456",
    name: "4th One",
    creation_date: new Date(),
    type: "Educational",
    contacts: [1, 2, 3, 4, 5],
  },
  {
    id: "123456",
    name: "5th One",
    creation_date: new Date(),
    type: "Governmental",
    contacts: [1, 2, 3, 4, 5],
  },
  {
    id: "123456",
    name: "6th One",
    creation_date: new Date(),
    type: "Governmental",
    contacts: [1, 2, 3, 4, 5],
  },
  {
    id: "123456",
    name: "7th One",
    creation_date: new Date(),
    type: "Educational",
    contacts: [1, 2, 3, 4, 5],
  },
  {
    id: "123456",
    name: "8th One",
    creation_date: new Date(),
    type: "Marketing",
    contacts: [1, 2, 3, 4, 5],
  },
  {
    id: "123456",
    name: "First One",
    creation_date: new Date(),
    type: "Governmental",
    contacts: [1, 2, 3, 4, 5],
  },
  {
    id: "123456",
    name: "Second One",
    creation_date: new Date(),
    type: "Marketing",
    contacts: [1, 2, 3, 4, 5],
  },
  {
    id: "123456",
    name: "3rd One",
    creation_date: new Date(),
    type: "Marketing",
    contacts: [1, 2, 3, 4, 5],
  },
  {
    id: "123456",
    name: "4th One",
    creation_date: new Date(),
    type: "Educational",
    contacts: [1, 2, 3, 4, 5],
  },
  {
    id: "123456",
    name: "5th One",
    creation_date: new Date(),
    type: "Governmental",
    contacts: [1, 2, 3, 4, 5],
  },
  {
    id: "123456",
    name: "6th One",
    creation_date: new Date(),
    type: "Governmental",
    contacts: [1, 2, 3, 4, 5],
  },
  {
    id: "123456",
    name: "7th One",
    creation_date: new Date(),
    type: "Educational",
    contacts: [1, 2, 3, 4, 5],
  },
  {
    id: "123456",
    name: "8th One",
    creation_date: new Date(),
    type: "Marketing",
    contacts: [1, 2, 3, 4, 5],
  },
];
